version: '3'
networks:
  fixtures_test:
    external: true
    name: fixtures_test

services:

  # zookeeper:
  #   image: wurstmeister/zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - fixtures_test

  # zoonavigator:
  #   image: elkozmon/zoonavigator:latest
  #   ports:
  #     - 2182:2182
  #   environment:
  #     ZOO_HOSTS: 'zookeeper:2181'
  #     HTTP_PORT: 2182
  #   links:
  #     - zookeeper
  #   networks:
  #     - fixtures_test

  # kafka0:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka0
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 0
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka0'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # kafka1:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka1
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka1'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # kafka2:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka2
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka2'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # kafka3:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka3
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka3'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test
  
  # kafka4:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka4
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 4
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka4'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka4:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # kafka5:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka5
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 5
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka5'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka5:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test
  
  # kafka6:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka6
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 6
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka6'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka6:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # kafka7:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka7
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 7
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka7'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka7:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test

  # centerkafka:
  #   image: wurstmeister/kafka:latest
  #   container_name: centerkafka
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 8
  #     AUTO_CREATE_TOPICS_ENABLE: 'true'
  #     DELETE_TOPIC_ENABLE: 'true'
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/centerkafka'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://centerkafka:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #   networks:
  #     - fixtures_test
  

  edgenode-peer0-org1:
    image: fabric-edgenode:latest
    container_name: edgenode-peer0-org1
    ports:
      - "7080:8080"
      - "7083:8083"
    volumes:
      - ./cfg/org1conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=15
      - LOCATION_Y=4
      - KAFKA_IP=kafka0:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb0:5984
      - PEER_NODE_NAME=peer0.org1.example.com:7051
      - ORG_ID=1
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test

  edgenode-peer1-org1:
    image: fabric-edgenode:latest
    container_name: edgenode-peer1-org1
    ports:
      - "7180:8080"
      - "7183:8083"
    volumes:
      - ./cfg/org1conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=7
      - LOCATION_Y=6
      - ZOOKEEPER_ADDR=zookeeper:2181
      - KAFKA_IP=kafka1:9092
      - COUCHDB_ADDR=http://admin:123456@couchdb1:5984
      - PEER_NODE_NAME=peer1.org1.example.com:8051
      - ORG_ID=1
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test

  edgenode-peer0-org2:
    image: fabric-edgenode:latest
    container_name: edgenode-peer0-org2
    ports:
      - "7280:8080"
      - "7283:8083"
    volumes:
      - ./cfg/org2conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=17
      - LOCATION_Y=12
      - KAFKA_IP=kafka2:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb2:5984
      - PEER_NODE_NAME=peer0.org2.example.com:9051
      - ORG_ID=2
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test

  edgenode-peer1-org2:
    image: fabric-edgenode:latest
    container_name: edgenode-peer1-org2
    ports:
      - "7380:8080"
      - "7383:8083"
    volumes:
      - ./cfg/org2conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=9
      - LOCATION_Y=14
      - KAFKA_IP=kafka3:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb3:5984
      - PEER_NODE_NAME=peer1.org2.example.com:10051
      - ORG_ID=2
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test
  
  edgenode-peer0-org3:
    image: fabric-edgenode:latest
    container_name: edgenode-peer0-org3
    ports:
      - "7480:8080"
      - "7483:8083"
    volumes:
      - ./cfg/org3conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=0
      - LOCATION_Y=15
      - KAFKA_IP=kafka4:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb4:5984
      - PEER_NODE_NAME=peer0.org3.example.com:11051
      - ORG_ID=3
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test
  
  edgenode-peer1-org3:
    image: fabric-edgenode:latest
    container_name: edgenode-peer1-org3
    ports:
      - "7580:8080"
      - "7583:8083"
    volumes:
      - ./cfg/org3conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=7
      - LOCATION_Y=18
      - KAFKA_IP=kafka5:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb5:5984
      - PEER_NODE_NAME=peer1.org3.example.com:12051
      - ORG_ID=3
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test
  
  edgenode-peer0-org4:
    image: fabric-edgenode:latest
    container_name: edgenode-peer0-org4
    ports:
      - "7680:8080"
      - "7683:8083"
    volumes:
      - ./cfg/org4conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=1
      - LOCATION_Y=3
      - KAFKA_IP=kafka6:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb6:5984
      - PEER_NODE_NAME=peer0.org4.example.com:13051
      - ORG_ID=4
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test
  
  edgenode-peer1-org4:
    image: fabric-edgenode:latest
    container_name: edgenode-peer1-org4
    ports:
      - "7780:8080"
      - "7783:8083"
    volumes:
      - ./cfg/org4conf.yaml:/conf/config.yaml
      - ./fixtures:/fixtures
      - ./kafka_crypto:/kafka_crypto
    environment:
      - LEFT_STORAGE=20
      - LOCATION_X=3
      - LOCATION_Y=7
      - KAFKA_IP=kafka7:9092
      - ZOOKEEPER_ADDR=zookeeper:2181
      - COUCHDB_ADDR=http://admin:123456@couchdb7:5984
      - PEER_NODE_NAME=peer1.org4.example.com:14051
      - ORG_ID=4
      - KEY_PATH=/fixtures/crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/msp/keystore/priv_sk
      - CENTER_ADDR=centerkafka:9092
    networks:
      - fixtures_test
    
  centernode:
    image: fabric-center:latest
    container_name: centernode
    environment:
      - KAFKA_ADDR=centerkafka:9092
      - COUCHDB_ADDR=http://admin:123456@couchdb-center:5984
    networks:
      - fixtures_test